/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import sdu.mdsd.tut1.ui.internal.Tut1Activator;

public class Tut1DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Tut1Activator.getInstance().getInjector("sdu.mdsd.tut1.Tut1Dsl");
	}

}
