/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathInterpreterScopeProvider extends DelegatingScopeProvider {
}
