/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTut1DslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(sdu.mdsd.tut1.tut1Dsl.Tut1DslPackage.eINSTANCE);
		return result;
	}
}
