/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MathInterpreterUiModule extends AbstractMathInterpreterUiModule {

	public MathInterpreterUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return MathInterpreterEObjectHoverProvider.class;
	}
}
