/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MathInterpreterUiModule extends AbstractMathInterpreterUiModule {

	public MathInterpreterUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
