/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Tut1DslUiModule extends AbstractTut1DslUiModule {

	public Tut1DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
