/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import sdu.mdsd.math.interpreter.MathInterpreterRuntimeModule;
import sdu.mdsd.math.interpreter.MathInterpreterStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MathInterpreterIdeSetup extends MathInterpreterStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MathInterpreterRuntimeModule(), new MathInterpreterIdeModule()));
	}
	
}
