/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.ide;


/**
 * Use this class to register ide components.
 */
public class MathInterpreterIdeModule extends AbstractMathInterpreterIdeModule {
}
