/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTut1DslScopeProvider extends DelegatingScopeProvider {
}
