/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import sdu.mdsd.math.interpreter.ui.internal.InterpreterActivator;

public class MathInterpreterUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return InterpreterActivator.getInstance().getInjector("sdu.mdsd.math.interpreter.MathInterpreter");
	}

}
