/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import sdu.mdsd.tut1.Tut1DslRuntimeModule;
import sdu.mdsd.tut1.Tut1DslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Tut1DslIdeSetup extends Tut1DslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Tut1DslRuntimeModule(), new Tut1DslIdeModule()));
	}
	
}
