/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.mathInterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Div</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sdu.mdsd.math.interpreter.mathInterpreter.MathInterpreterPackage#getDiv()
 * @model
 * @generated
 */
public interface Div extends FactorOp
{
} // Div
