/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.mathInterpreter;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sdu.mdsd.math.interpreter.mathInterpreter.Exp#getLeft <em>Left</em>}</li>
 *   <li>{@link sdu.mdsd.math.interpreter.mathInterpreter.Exp#getOperator <em>Operator</em>}</li>
 *   <li>{@link sdu.mdsd.math.interpreter.mathInterpreter.Exp#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see sdu.mdsd.math.interpreter.mathInterpreter.MathInterpreterPackage#getExp()
 * @model
 * @generated
 */
public interface Exp extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(EObject)
   * @see sdu.mdsd.math.interpreter.mathInterpreter.MathInterpreterPackage#getExp_Left()
   * @model containment="true"
   * @generated
   */
  EObject getLeft();

  /**
   * Sets the value of the '{@link sdu.mdsd.math.interpreter.mathInterpreter.Exp#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(EObject value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' containment reference.
   * @see #setOperator(ExpOp)
   * @see sdu.mdsd.math.interpreter.mathInterpreter.MathInterpreterPackage#getExp_Operator()
   * @model containment="true"
   * @generated
   */
  ExpOp getOperator();

  /**
   * Sets the value of the '{@link sdu.mdsd.math.interpreter.mathInterpreter.Exp#getOperator <em>Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' containment reference.
   * @see #getOperator()
   * @generated
   */
  void setOperator(ExpOp value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Factor)
   * @see sdu.mdsd.math.interpreter.mathInterpreter.MathInterpreterPackage#getExp_Right()
   * @model containment="true"
   * @generated
   */
  Factor getRight();

  /**
   * Sets the value of the '{@link sdu.mdsd.math.interpreter.mathInterpreter.Exp#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Factor value);

} // Exp
