/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.mathInterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Left</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sdu.mdsd.math.interpreter.mathInterpreter.ExpLeft#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see sdu.mdsd.math.interpreter.mathInterpreter.MathInterpreterPackage#getExpLeft()
 * @model
 * @generated
 */
public interface ExpLeft extends Exp
{
  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Factor)
   * @see sdu.mdsd.math.interpreter.mathInterpreter.MathInterpreterPackage#getExpLeft_Right()
   * @model containment="true"
   * @generated
   */
  Factor getRight();

  /**
   * Sets the value of the '{@link sdu.mdsd.math.interpreter.mathInterpreter.ExpLeft#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Factor value);

} // ExpLeft
