/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.mathInterpreter;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sdu.mdsd.math.interpreter.mathInterpreter.MathInterpreterPackage#getPrimary()
 * @model
 * @generated
 */
public interface Primary extends EObject
{
} // Primary
