/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.tut1Dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sdu.mdsd.tut1.tut1Dsl.Tut1DslPackage#getAbstractElement()
 * @model
 * @generated
 */
public interface AbstractElement extends EObject
{
} // AbstractElement
