/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.tut1Dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sdu.mdsd.tut1.tut1Dsl.Tut1DslPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
