/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import sdu.mdsd.math.interpreter.ui.internal.InterpreterActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathInterpreterExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(InterpreterActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		InterpreterActivator activator = InterpreterActivator.getInstance();
		return activator != null ? activator.getInjector(InterpreterActivator.SDU_MDSD_MATH_INTERPRETER_MATHINTERPRETER) : null;
	}

}
