/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MathInterpreterRuntimeModule extends AbstractMathInterpreterRuntimeModule {
}
