/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MathInterpreterStandaloneSetup extends MathInterpreterStandaloneSetupGenerated {

	public static void doSetup() {
		new MathInterpreterStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
