/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.math.interpreter.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sdu.mdsd.math.interpreter.parser.antlr.internal.InternalMathInterpreterParser;
import sdu.mdsd.math.interpreter.services.MathInterpreterGrammarAccess;

public class MathInterpreterParser extends AbstractAntlrParser {

	@Inject
	private MathInterpreterGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMathInterpreterParser createParser(XtextTokenStream stream) {
		return new InternalMathInterpreterParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MathExp";
	}

	public MathInterpreterGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathInterpreterGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
