/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Tut1DslRuntimeModule extends AbstractTut1DslRuntimeModule {
}
