/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class Tut1DslProposalProvider extends AbstractTut1DslProposalProvider {
}
