/**
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.tut1Dsl.impl;

import org.eclipse.emf.ecore.EClass;

import sdu.mdsd.tut1.tut1Dsl.DataType;
import sdu.mdsd.tut1.tut1Dsl.Tut1DslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DataTypeImpl extends TypeImpl implements DataType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Tut1DslPackage.Literals.DATA_TYPE;
  }

} //DataTypeImpl
