/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Tut1DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("sdu/mdsd/tut1/parser/antlr/internal/InternalTut1Dsl.tokens");
	}
}
