/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sdu.mdsd.tut1.parser.antlr.internal.InternalTut1DslParser;
import sdu.mdsd.tut1.services.Tut1DslGrammarAccess;

public class Tut1DslParser extends AbstractAntlrParser {

	@Inject
	private Tut1DslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTut1DslParser createParser(XtextTokenStream stream) {
		return new InternalTut1DslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public Tut1DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Tut1DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
