/*
 * generated by Xtext 2.24.0
 */
package sdu.mdsd.tut1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import sdu.mdsd.tut1.ui.internal.Tut1Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Tut1DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Tut1Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Tut1Activator activator = Tut1Activator.getInstance();
		return activator != null ? activator.getInjector(Tut1Activator.SDU_MDSD_TUT1_TUT1DSL) : null;
	}

}
